name: remusic
description: "A modern audio file management tool with batch renaming, tag editing, and audio resampling"
publish_to: 'none'

version: 0.1.0+25

environment:
  sdk: ^3.10.8
  flutter: ">=3.38.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  audio_metadata_reader: ^1.4.2
  provider: ^6.1.2
  path: ^1.9.1
  file_picker: ^10.3.10
  window_manager: ^0.5.1
  audiotags: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  generate: true

  fonts:
    - family: HanYiJiaShuJian
      fonts:
        - asset: assets/fonts/HYJiaShu-55U.ttf

  assets:
    - assets/images/Logos/1024.png
